### ISSUE TITLE
ERROR: You must install PyTorch prior to installing DensePose

### ISSUE THREAD

**Issue by nitinmukesh** [Flode-Labs/vid2densepose#24]
Don't understand what is the issue. Followed the steps mentioned in Readme

```
(venv) C:\tut\vid2densepose>pip install git+https://github.com/facebookresearch/detectron2@main#subdirectory=projects/DensePose
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Collecting git+https://github.com/facebookresearch/detectron2@main#subdirectory=projects/DensePose
  Cloning https://github.com/facebookresearch/detectron2 (to revision main) to c:\users\nitin\appdata\local\temp\pip-req-build-g93v9uik
  Running command git clone --filter=blob:none --quiet https://github.com/facebookresearch/detectron2 'C:\Users\nitin\AppData\Local\Temp\pip-req-build-g93v9uik'
  Resolved https://github.com/facebookresearch/detectron2 to commit 92ae9f0b92aba5867824b4f12aa06a22a60a45d3
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [29 lines of output]
      Traceback (most recent call last):
        File "<string>", line 6, in <module>
      ModuleNotFoundError: No module named 'torch'

      The above exception was the direct cause of the following exception:

      Traceback (most recent call last):
        File "C:\tut\vid2densepose\venv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\tut\vid2densepose\venv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\tut\vid2densepose\venv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\nitin\AppData\Local\Temp\pip-build-env-uixtj06r\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "C:\Users\nitin\AppData\Local\Temp\pip-build-env-uixtj06r\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\nitin\AppData\Local\Temp\pip-build-env-uixtj06r\overlay\Lib\site-packages\setuptools\build_meta.py", line 487, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\nitin\AppData\Local\Temp\pip-build-env-uixtj06r\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 8, in <module>
      Exception:
      You must install PyTorch prior to installing DensePose:
      pip install torch

      For more information:
          https://pytorch.org/get-started/locally/

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

```

**pip list**

```
absl-py                   2.1.0
aiofiles                  23.2.1
altair                    5.3.0
annotated-types           0.6.0
antlr4-python3-runtime    4.9.3
anyio                     4.3.0
attrs                     23.2.0
av                        12.0.0
black                     24.4.2
certifi                   2024.2.2
charset-normalizer        3.3.2
click                     8.1.7
cloudpickle               3.0.0
colorama                  0.4.6
contourpy                 1.2.1
cycler                    0.12.1
exceptiongroup            1.2.1
fastapi                   0.110.3
ffmpy                     0.3.2
filelock                  3.14.0
fonttools                 4.51.0
fsspec                    2024.3.1
fvcore                    0.1.5.post20221221
gradio                    4.28.3
gradio_client             0.16.0
grpcio                    1.62.2
h11                       0.14.0
httpcore                  1.0.5
httpx                     0.27.0
huggingface-hub           0.22.2
hydra-core                1.3.2
idna                      3.7
importlib_resources       6.4.0
iopath                    0.1.9
Jinja2                    3.1.3
jsonschema                4.21.1
jsonschema-specifications 2023.12.1
kiwisolver                1.4.5
Markdown                  3.6
markdown-it-py            3.0.0
MarkupSafe                2.1.5
matplotlib                3.8.4
mdurl                     0.1.2
mpmath                    1.3.0
mypy-extensions           1.0.0
networkx                  3.3
numpy                     1.26.4
omegaconf                 2.3.0
opencv-python             4.9.0.80
opencv-python-headless    4.9.0.80
orjson                    3.10.1
packaging                 24.0
pandas                    2.2.2
pathspec                  0.12.1
pillow                    10.3.0
pip                       24.0
platformdirs              4.2.1
portalocker               2.8.2
protobuf                  5.26.1
pycocotools               2.0.7
pydantic                  2.7.1
pydantic_core             2.18.2
pydub                     0.25.1
Pygments                  2.17.2
pyparsing                 3.1.2
python-dateutil           2.9.0.post0
python-multipart          0.0.9
pytz                      2024.1
pywin32                   306
PyYAML                    6.0.1
referencing               0.35.0
requests                  2.31.0
rich                      13.7.1
rpds-py                   0.18.0
ruff                      0.4.2
scipy                     1.13.0
semantic-version          2.10.0
setuptools                63.2.0
shellingham               1.5.4
six                       1.16.0
sniffio                   1.3.1
starlette                 0.37.2
sympy                     1.12
tabulate                  0.9.0
tensorboard               2.16.2
tensorboard-data-server   0.7.2
termcolor                 2.4.0
tomli                     2.0.1
tomlkit                   0.12.0
toolz                     0.12.1
torch                     2.1.0+cu121
torchvision               0.16.0+cu121
tqdm                      4.66.2
typer                     0.12.3
typing_extensions         4.11.0
tzdata                    2024.1
urllib3                   2.2.1
uvicorn                   0.29.0
websockets                11.0.3
Werkzeug                  3.0.2
yacs                      0.1.8

```

**Comment by learnuser1** [comment]
hello，I have the same problem. What do you do to solve it?

**Comment by mwxiaomao** [comment]
本地源码安装，试一试 python -m pip install -e detectron2 --no-build-isolation
