### ISSUE TITLE
ModuleNotFoundError: No module named 'detectron2.config'

### ISSUE THREAD

**Issue by alexfredo** [Flode-Labs/vid2densepose#4]
Hi I have a error when I use the "py main.py" command, the error : 

 File "C:\vid2densepose\main.py", line 1, in <module>
    from detectron2.config import get_cfg
ModuleNotFoundError: No module named 'detectron2.config'

Please helps ! thanks

**Comment by alexfredo** [comment]
Yes I tried but I have a error when I pip install the requirement too : 
![ffferror](https://github.com/Flode-Labs/vid2densepose/assets/24534698/2bb1cfd2-f9e3-47e1-a4db-13ab7fad9fb6)

**Comment by alexfredo** [comment]
I have windows 10 too

**Comment by tadeodonegana** [comment]
Have you cloned the Detectron repository?  

Please use  `git clone https://github.com/facebookresearch/detectron2.git` as specified in the readme.

**Comment by Questscape** [comment]
yes i cloned and installed the detectron repo, installed it, now im getting: 
`Traceback (most recent call last):
  File "G:\magic_animate\magic-animate\video2dense\vid2densepose\app.py", line 7, in <module>
    from densepose import add_densepose_config
ModuleNotFoundError: No module named 'densepose'`

**Comment by igorriti** [comment]
The issue lies with Windows, and while we are actively working on a solution, I would recommend utilizing Windows Subsystem for Linux (WSL) as a temporary workaround. You can easily download WSL from the Microsoft Store, and it functions seamlessly. I will also include this advice in the readme for your convenience.

**Comment by chen-rn** [comment]
I'm on OSX Ventura and am running into the same issue as well.

**Comment by igorriti** [comment]
I cannot reproduce your problem @zono50 , could you provide us with more details? Which version of torch and torch vision did you have? 

I suggest you to create a virtual env, git clone the detectron repo, then install the torch and torch vision(check the requirements.txt for the versions) and finally the pip install - r requirements.txt

**Comment by ljzm** [comment]
> 您是否克隆了 Detectron 存储库？
> 
> 请按照自述文件中的规定使用。`git clone https://github.com/facebookresearch/detectron2.git`

请问这个仓库git clone下来应该放在哪个目录下，放在vid2densepose目录下吗，还是同级？期待答复。谢谢

**Comment by harpy2** [comment]
!apt install -y nvidia-cuda-dev

**Comment by ml1969** [comment]
Hi,
I trioed to install it under windows like @alexfredo and I got the same errormessage.
After that, I tried to use WSL with Ubuntu under Win11.
I´m a noob. I do not get it to work.
At first I realised that there are some packeges missing :(
At least I installed the wrong CUD Version, and so on.

I will try it on a fresh WSL installation,

For me the best solution will be, no erros under windows 👯 

Regards
michael
